### ISSUE TITLE
question/wrglhub

### ISSUE THREAD

**Issue by ayyubibrahimi** [ppact/processing#216] opened 2021-12-20 22:14 UTC
@pckhoi 

Working on integrating wrgl now. The current steps that I've taken:

1) Installed with: sudo bash -c 'curl -L https://github.com/wrgl/wrgl/releases/latest/download/install.sh | bash'
2) initialized a repo with `wrgl init`
3) Set up credentials
3) Attempted to `wrgl pull --all`, however, I received the following error: 

```
wrgl pull --all
pulling allegation...
No credential found for https://hub.wrgl.co/api/users/ipno/repos/allegation
Run this command to authenticate:
    wrgl credentials authenticate https://hub.wrgl.co/api/users/ipno/repos/allegation
unauthorized
```
After running `wrgl credentials authenticate https://hub.wrgl.co/api/users/ipno/repos/allegation`, I receive the following message: 

```
wrgl credentials authenticate https://hub.wrgl.co/api/users/ipno/repos/allegation
Enter your email and password for https://hub.wrgl.co/api/users/ipno/repos/allegation.
Email: ayyubi@ip-no.org
Password: 
status 404: {"message":"Not Found"}
```
I have confirmed that my password is correct by logging into hub.wrgl. Thoughts? Thanks!

**Comment by pckhoi** [comment] 2021-12-21 00:26
Can you try with this?
```bash
wrgl credentials authenticate https://hub.wrgl.co/api
```

**Comment by ayyubibrahimi** [comment] 2021-12-21 01:09
Yes, I will try and update you tonight.

**Comment by ayyubibrahimi** [comment] 2021-12-21 02:45
Cool. I'm in. Will let you know if I run into any other questions along the way.

**Comment by ayyubibrahimi** [comment] 2021-12-21 03:21
Current issue that I have yet to figure out how to solve. Please advise. The following error was raised at the tail end of make:

`make: *** No rule to make target 'build/person.csv', needed by 'data/match/person.csv'.  Stop.`

**Comment by pckhoi** [comment] 2021-12-21 09:21
I fixed it in https://github.com/ppact/processing/pull/218

Please check out that branch and see if it work for you.

**Comment by ayyubibrahimi** [comment] 2021-12-22 00:48
Currently in progress. Wifi is terribly slow, so it's taking a while but I'll shoot over an update when I have one.

**Comment by ayyubibrahimi** [comment] 2021-12-22 01:29
Looks good!

**Comment by ayyubibrahimi** [comment] 2021-12-22 17:55
Keeping this open for when I have inevitable questions that'll come to me prior to making the first push, which I think makes sense after we finalize POST, which I'm going to review now and ask for your review, once more, if it looks complete.

**Comment by ayyubibrahimi** [comment] 2022-01-02 20:20
@pckhoi 

In the process of making a commit to wrglhub now that the POST data has been integrated successfully. 

Just ran` wrgl pull --all` and I notice that some branches are labeled as "Repository not found, skipping." Not 100% sure as to what this means.

**Comment by ayyubibrahimi** [comment] 2022-01-02 20:43
Q. When making a commit to wrglhub, should I be making it from the main git branch?

**Comment by ayyubibrahimi** [comment] 2022-01-02 21:35
The running of `wrgl diff --all` stops completely when it comes across the following:

```
match-pprr-st-tammany-so-2020 changes:
open data/match/pprr_st_tammany_so_2020.csv: no such file or directory
```

If I remember correctly, some of these `match/pprr_(x_agency).csv` files were removed when you introduced the `extract post events` function, because we decided to prioritize pprr data collected directly from a given agency over POST, which made the  `match/pprr_(x_agency).csv` unnecessary.

**Comment by ayyubibrahimi** [comment] 2022-01-02 21:54
Running `make`, which I ran prior to wrglhub comparisons, doesn't seem to be working as intended, as I've received the following break when running `wrgl diff --all`

```
baton-rouge-da-brady-list changes:
open data/match/cprr_baton_rouge_da_2021.csv: no such file or directory
```
If I run within the terminal `make data/match/cprr_baton_rouge_da_2021.csv`, the error is no longer present when I run  `wrgl diff --all`.

**Comment by pckhoi** [comment] 2022-01-03 00:39
There is a new version of wrgl with better diff output. Please install with:
```
sudo bash -c 'curl -L https://github.com/wrgl/wrgl/releases/latest/download/install.sh | bash'
```

When commit & push, please do so from the `main` branch.

`Repository not found, skipping.` during pulling simply means the corresponding repo for a branch is not yet created on wrglhub. The latest version has the command `wrgl hub repo create` created just for this purpose. You can run it when you add new entries to the `remotes` section.

It seems that make is running as intended. Only outputs of fuse scripts are automatically included in the `all` target of make. If you want to include other files then please add them as a dependency of `all` target.

**Comment by pckhoi** [comment] 2022-01-03 00:43
Actually, please hold off on running `wrgl hub repo create`. I need to add a flag to specify the owner (other than yourself) e.g. `--user ipno`.

**Comment by ayyubibrahimi** [comment] 2022-01-03 00:46
Ok.

**Comment by pckhoi** [comment] 2022-01-03 01:41
New version of `wrgl` is released with `--user` flag for `wrgl hub repo create`.

**Comment by ayyubibrahimi** [comment] 2022-01-03 03:27
I ran `sudo bash -c 'curl -L https://github.com/wrgl/wrgl/releases/latest/download/install.sh | bash`

I ran `wrgl pull --all`  again;

I next ran `wrgl diff --all`. The break message is now:

```
open data/match/pprr_brusly_pd_2020.csv: no such file or directory
```

**Comment by ayyubibrahimi** [comment] 2022-01-03 06:08
Because these `match/pprr_(x_agency).csv` are no longer relevant for some agencies (namely Brusly and St Tammany), now that the `extract_post_events_function `is in use, I'm working in an experimental branch where I have removed these `match/pprr `outputs from the config.yaml file and` wrgl diff --all `  now runs without the breaks noted above. 
 
Am I on the right track?

**Comment by pckhoi** [comment] 2022-01-03 23:44
Yes, please make the changes in a new PR. I have already reviewed the output though so feel free to push now.

**Comment by ayyubibrahimi** [comment] 2022-01-04 05:36
I run: `wrgl commit per-post 'integrating per-post into ipnos wrglhub repo` and receive the following output: 

```
⠹ sorting (33809/-, 126796 it/s)
⠼ saving blocks (133/-, 290 it/s)
[per-post 18a07b7] integrating per-post into ipnos wrglhub repo
```

I then run: `wrgl push per-post`, and receive the following output: 

`status 404: {"message":"Not Found"}`

Please advise as to what silly mistake I am making

**Comment by pckhoi** [comment] 2022-01-04 12:50
Maybe because the per-post repository does not exist on wrglhub? You can create that repo with:
```
wrgl hub repo create per-post --user ipno
```

Regarding the commit and diff command, did they stop when the file isn't found? If so then I will make them continue with other branches in a new version.

**Comment by ayyubibrahimi** [comment] 2022-01-04 13:34
That makes perfect sense. Thank you. I wasn't able to locate that command in the READMEcor documentation page for wrglhub (which looks awesome, btw)

Re your question: yes

**Comment by ayyubibrahimi** [comment] 2022-01-04 14:52
Fully up to-date. Thanks for the walk through. 

One q. The new repo's, for example, `per-post` has automatically been classified as private. Is this intentional?

**Comment by pckhoi** [comment] 2022-01-04 16:31
Sorry I forgot to mention that you need to add the flag `--public` during repo creation. If you cannot change it to public then perhaps ipno handle (which I'm still holding) will be able to change it.

**Comment by pckhoi** [comment] 2022-01-04 16:35
Re documentation page, it is still tied to wrglhub release schedule for now so it is a little delayed. But you can access most of the same documentation for any command if you just add `--help` flag.

**Comment by ayyubibrahimi** [comment] 2022-01-04 16:36
All good. I'll look into manual changes. Thanks!

**Comment by ayyubibrahimi** [comment] 2022-01-05 20:23
I don't seem to be able to change it manually.

**Comment by ayyubibrahimi** [comment] 2022-01-06 00:15
Regarding the appeal_hearing and acadia_so branches that were merged into main today, I can created (public :) ) wrgl repos for appeal-hearing and acadia, committed and then ran `wrgl push --all`. A break occurred at: 

```
pushing sas-new-orleans-pd...
To https://hub.wrgl.co/api/users/ipno/repos/sas-new-orleans-pd
status 413: <html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
Should I only be running `wrgl push --all ` when absolutely necessary?

**Comment by pckhoi** [comment] 2022-01-06 00:26
@ayyubibrahimi the only way to make a repo public for now is to do so on the user page: https://hub.wrgl.co/@ipno if you have the ipno handle. I went ahead and make these 3 repos public: `per-post`, `per-baker-pd`, `per-abbleville-pd`.

`413 Request Entity Too Large` means the data you're pushing is too big so the server refuses to accept. It's a simple exercise to increase the payload size that it accepts. How many row? What is the size of the file?

**Comment by ayyubibrahimi** [comment] 2022-01-06 00:29
I'll go ahead and make the rest public. Thanks. 

Size of `sas-new-orleans-pd` is 240 MB (252,231,930 bytes)

**Comment by pckhoi** [comment] 2022-01-07 08:18
@ayyubibrahimi I have increased the max payload size. Can you try pushing again and let me know how it goes?

**Comment by ayyubibrahimi** [comment] 2022-01-07 17:13
It worked! Awesome. Thanks. Repo design changes look great. Killin it.

**Comment by pckhoi** [comment] 2022-01-08 00:58
Thank you!

**Closed** 2022-01-09 19:39 UTC
